### PR TITLE
49 optimize dashboard layout

### PR DESCRIPTION
**Pull request by monazhu**
- optimize dashboard layout
image

- adjust colour scheme in css styling
- update demo GIF

### CODE REVIEW

**Comment by juliaeveritt** [comment]
I think the filter on the left feels intuitive! Colour on the header could be good but I think it looks nice as is too

**Comment by monazhu** [comment]
I tried playing around with adding a colour block to the header, instead of the widget, but I don't think it really helped. I found that having a colour bg in both was pretty distracting and you end up not focusing on the outputs. I'm also not super married to the current widget colour scheme (I think maybe a grey background might actually be better).

**Comment by farrandi** [comment]
Sounds good, do you have an example screenshot of a gray background?

**Comment by monazhu** [comment]
yah here it is! i think this looks better than what i had before. 
image

**Comment by juliaeveritt** [comment]
Big fan of the grey! That looks great

**Comment by monazhu** [comment]
Yeah I think I like this better (was trying to see if I could get the other palette to work but I think it just looked too busy or tacky). If you guys are okay with this new colour scheme, I'll push the changes to the branch!

**Comment by juliaeveritt** [comment]
That would be amazing! Thanks so much Mona!

**Review by juliaeveritt — APPROVED** [review]
Love the side bar and the updated grey background

**Review by farrandi — APPROVED** [review]
Gray looks great!

**Comment by farrandi** [comment]
Whoops, Just merged it but noticed that the gif in the read me was not updated. @monazhu Could you make another PR to fix it?

**Comment by monazhu** [comment]
Yayaya I'll do that in a bit!

**Comment by Rachel0619** [comment]
The one with grey sidebar on the left looks perfect to me!

**Pull request merged**
