### PR TITLE
made simple mvp for dashboard

### PR DESCRIPTION
**Pull request by farrandi**
- Add world map
- Add slider for years selection
- Add dropdown for country selection
- Add chart for temp and co2 vs time
- Add chart for top Co2 emitters

Still need to:
- Rearrange the charts
- Make sure the charts have responsive sizing

Preview:
image

### CODE REVIEW

**Comment by Rachel0619** [comment]
Great draft at this point!
Possible tiny adjustment we want to make is arrange the layout of the dashboard so that each block aligns with each other neatly horizontally and vertically. But this draft is a good start!

**Review by Rachel0619 — COMMENTED** [review]
Great draft at this point!
Possible tiny adjustment we want to make is arrange the layout of the dashboard so that each block aligns with each other neatly horizontally and vertically. But this draft is a good start!

**Review by monazhu — APPROVED** [review]
The MVP looks great! Pulling changes through :)

**Comment by juliaeveritt** [comment]
Looks great!! One other small adjustment is to add units to the axis labels on Top CO2 Emitters and Temp&CO2 over time plots

**Pull request merged**
