### PR TITLE
added figure note for global_temp_co2 plot, added loading animation

### PR DESCRIPTION
**Pull request by monazhu**
- Add figure caption for `glonal_temp_co2` plot
- Add loading animation for outputs while plots are updating

### CODE REVIEW

**Review by farrandi — APPROVED** [review]
I like that you added the loading part.

LGTM

**Comment by farrandi** [comment]
For some reason, when I check the render file, there is no emission and temperature graph.

**Comment by monazhu** [comment]
> For some reason, when I check the render file, there is no emission and temperature graph.

yeah that's what i'm trying to fix right now (which is why i messaged to say not to merge just yet 😂)

**Comment by monazhu** [comment]
Okay issue resolved! Branch should be good to be merged with main

**Comment by farrandi** [comment]
Ok tested it! It works great!

Just reformatted some code based on python linter

**Pull request merged**
