### PR TITLE
23 create gif animation of use case

### PR DESCRIPTION
**Pull request by monazhu**
Made some adjustments to the dashboard to allow for better readability and screen recorded GIF after tweaks were made. I also added the gif to the README file. 

Let me know if there's anything you want me to change!

### CODE REVIEW

**Review by farrandi — APPROVED** [review]
LGTM

**Comment by farrandi** [comment]
I am not able to open the render URL above though. @monazhu

**Comment by monazhu** [comment]
> I am not able to open the render URL above though. @monazhu

Oh weird - I followed what's in the lecture notes for this section but maybe I'll ask Joel about it today...

**Comment by farrandi** [comment]
The link works. It just takes forever to load.

**Pull request merged**
